# Generated by Django 5.0.6 on 2024-06-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='product_service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
