# Generated by Django 5.0.6 on 2024-06-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='working_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
