# Generated by Django 5.0.6 on 2024-06-29 14:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_working_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('invoice_email', models.EmailField(max_length=254)),
                ('invoice_address', models.TextField()),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('pay_later', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('primary_tag', models.CharField(max_length=255)),
                ('location_restriction', models.CharField(max_length=255)),
                ('annual_salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_description', models.TextField()),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('apply_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('benefits', models.TextField()),
                ('how_to_apply', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.job')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
