# Generated by Django 5.0.6 on 2024-07-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_jobapplication_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hiring_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='how_heard_about_codeunity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('freelance', 'Freelance Contractor'), ('full_time', 'Full Time Employee')], max_length=50, null=True),
        ),
    ]
