# Generated by Django 5.0.6 on 2024-07-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_hiring_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
