# Generated by Django 5.0.6 on 2024-07-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='looking_for',
        ),
    ]
