# Generated by Django 5.0.6 on 2024-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_customuser_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('freelance', 'Freelance Contractor'), ('full_time', 'Full Time Employee')], max_length=10, null=True),
        ),
    ]
