# Generated by Django 5.0.6 on 2024-07-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_looking_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='working_email',
        ),
    ]
