# Generated by Django 5.0.6 on 2024-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_customuser_working_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='working_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
