# Generated by Django 5.0.6 on 2024-05-23 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('invoice_email', models.EmailField(max_length=254)),
                ('invoice_address', models.TextField()),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('pay_later', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('primary_tag', models.CharField(max_length=255)),
                ('location_restriction', models.CharField(max_length=255)),
                ('annual_salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_description', models.TextField()),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('apply_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('benefits', models.TextField()),
                ('how_to_apply', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
