# Generated by Django 5.0.6 on 2024-07-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_delete_document_job_posted_by_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
